### ISSUE TITLE
don't work : no authorisation  Location

### ISSUE THREAD

**Issue by songotag** [pgiacomo69/flutter_esp32_ble#1]
I tried to make it works on my galaxy s6 and my huawei p20 pro phones, no luck 
When i click send  i've this message : 

`Exception : GenericFailure<scanFailure> ( code : Scanfailure, unknow, message : "Location Permission missing ( code 3 )")`

the bluetooth ans GPS location are ON

Do you know where is the prblem ?

**Comment by pgiacomo69** [comment]
Sorry, I forgot to answer, you have to enable location permission for the app from android settings

**Comment by songotag** [comment]
Thanks for you response, is there any solution to enable it automaticaly ?

It does not work with androidmanifest file.

**Comment by pgiacomo69** [comment]
Still don't know, I hadn't the time to investigate more, didn't you find a solution online? Time ago I searched it, I see that is a common problem.

**Comment by songotag** [comment]
I've compared your program with a flutter base program and i don't find any solution.
I think because is probably base on a deprecated " flutter_reactive_ble"

**Comment by pgiacomo69** [comment]
What is deprecated? The flutter_reactive_ble project?

**Comment by songotag** [comment]
oops, sorry, I got the wrong compilation window about the deprecated library.
